/*Object Literals:

Object has properties and methods. A property is like a variable that belongs to the object, and a method is something the object can "do," or that can be "done" to the object. In this video, you'll learn the syntax for creating an object literal that stores data as property/value pairs.

Has PROPERTIES AND METHODS:

properties: like a variable
method: something the object can do


STORING DATA WITH OBJECTS
-object single item that holds multiple variables. 

KEY(OR PROPERTY) IS LIKE A VARIABLE NAME, 
VALUE IS LIKE THE VALUE OF THAT VARIABLE. 

*/

// HOW TO BUILD - ASSIGN AN OBJECT LITERAL BETWEEN { }

const = {
    name: "Quincy",
    //   key: value 
    grades: [83, 34, 34, 564]
}